# Generated by Django 5.2.15 on 2026-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the supplier company.', max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person name.', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical or billing address.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this supplier is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
