# Generated by Django 5.2.15 on 2026-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='total_units_received',
            field=models.PositiveIntegerField(default=0, help_text='Calculated as quantity * medicine.units_per_package'),
        ),
    ]
