# Generated by Django 5.2.15 on 2026-07-23 16:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseitem_total_units_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='package_type',
            field=models.CharField(default='Unit', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='units_per_package',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total_units_received',
            field=models.PositiveIntegerField(default=0, help_text='Calculated as quantity * units_per_package'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
