# Generated by Django 5.2.5 on 2026-07-06 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0003_medicine_minimum_stock_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('location', models.CharField(blank=True, help_text='Optional physical location (e.g. Shelf A, Room 2)', max_length=255, null=True, verbose_name='Storage Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='medicines.medicine', verbose_name='Medicine')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Added', 'Added'), ('Adjusted', 'Adjusted'), ('Removed', 'Removed'), ('Expired', 'Expired')], max_length=20, verbose_name='Action')),
                ('quantity_before', models.IntegerField(verbose_name='Quantity Before')),
                ('quantity_after', models.IntegerField(verbose_name='Quantity After')),
                ('quantity_changed', models.IntegerField(verbose_name='Quantity Changed')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged At')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='inventory.inventory', verbose_name='Inventory Batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_actions', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Inventory History',
                'verbose_name_plural': 'Inventory Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
