# Generated by Django 5.2.15 on 2026-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes / Remarks'),
        ),
    ]
