# Generated by Django 5.2.15 on 2026-07-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['medicine__name'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
    ]
