# Generated by Django 5.2.15 on 2026-07-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Antibiotics, Analgesics, Vitamins', max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this category covers.', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Generic or brand name of the medicine.', max_length=200, verbose_name='Medicine Name')),
                ('brand', models.CharField(blank=True, help_text='Manufacturer brand name, if different from generic name.', max_length=200, null=True, verbose_name='Brand Name')),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup (ml)'), ('injection', 'Injection (ml)'), ('cream', 'Cream (g)'), ('drops', 'Drops (ml)'), ('sachet', 'Sachet'), ('other', 'Other')], default='tablet', help_text='How this medicine is measured/dispensed.', max_length=20, verbose_name='Unit of Measurement')),
                ('requires_prescription', models.BooleanField(default=False, help_text='If True, cashiers must request a prescription before selling.', verbose_name='Requires Prescription')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit paid to supplier.', max_digits=10, verbose_name='Purchase Price (Rs.)')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Retail price per unit charged to customers.', max_digits=10, verbose_name='Selling Price (Rs.)')),
                ('description', models.TextField(blank=True, help_text='Optional notes on usage, dosage, or side effects.', null=True, verbose_name='Description / Usage')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive medicines are hidden from sales and inventory views.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
    ]
