# Generated by Django 5.2.5 on 2026-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_category_is_active_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=10, help_text='The threshold level below which stock is considered low.', verbose_name='Minimum Stock Level'),
        ),
    ]
