# Generated by Django 5.2.15 on 2026-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_minimum_stock_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='unit',
            new_name='sellable_unit',
        ),
        migrations.AddField(
            model_name='medicine',
            name='purchase_package_type',
            field=models.CharField(choices=[('Strip', 'Strip'), ('Packet', 'Packet'), ('Box', 'Box'), ('Bottle', 'Bottle'), ('Carton', 'Carton'), ('Unit', 'Unit')], default='Unit', help_text='How this medicine is purchased (e.g. Box, Strip).', max_length=50, verbose_name='Purchase Package Type'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='units_per_package',
            field=models.PositiveIntegerField(default=1, help_text='Number of sellable units inside one purchase package.', verbose_name='Units per Package'),
        ),
    ]
