# Generated by Django 5.2.15 on 2026-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_remove_medicine_unit_medicine_purchase_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='sellable_unit',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup (ml)'), ('injection', 'Injection (ml)'), ('cream', 'Cream (g)'), ('drops', 'Drops (ml)'), ('sachet', 'Sachet'), ('piece', 'Piece'), ('other', 'Other')], default='tablet', help_text='How this medicine is measured/dispensed.', max_length=20, verbose_name='Sellable Unit'),
        ),
    ]
